shopproject/onlineshop/apps/accounts/urls.py
from django.urls import path
import apps.accounts.views as views

app_name='accounts'
urlpatterns=[
    path('register/',views.RegisterUserView.as_view(),name='register'),
    path('login/',views.LoginUserView.as_view(),name='login'),
    path('logout/',views.LogoutUserView.as_view(),name='logout'),
    
]
    

shopproject/onlineshop/apps/cart/urls.py
from django.urls import path
import apps.cart.views as views

app_name='cart'
urlpatterns=[
    path('',views.cart_summary,name='cart_summary'),
    path('add/',views.cart_add,name='cart_add'),
    path('delete/',views.cart_delete,name='cart_delete'),
    path('update/',views.cart_update,name='cart_update'),
    
]

shopproject/onlineshop/apps/main/urls.py
from django.urls import path
import apps.main.views as views

app_name='main'
urlpatterns=[
    path('',views.ProductList.as_view(),name='index'),
    path('products/',views.ProductList.as_view(),name='products'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('about/',views.about,name='about'),
]
    

shopproject/onlineshop/apps/order/urls.py
from django.urls import path
import apps.order.views as views


app_name='order'

urlpatterns=[
    path('order_list/',views.order_list,name='order_list'),
    path('create_order/',views.create_order,name='create_order'),
    # path('create_order/<int:order_id>/',views.create_order, name='create_order'),
]

shopproject/onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [        
        path('admin/', admin.site.urls),
        path('',include('apps.main.urls',namespace='main'),name='main'),
        path('products/',include('apps.products.urls',namespace='products'),name='products'),
        path('search/',include('apps.search.urls',namespace='search'),name='search'),
        path('accounts/',include('apps.accounts.urls',namespace='accounts'),name='accounts'),
        path('cart/',include('apps.cart.urls',namespace='cart'),name='cart'),
        path('order/',include('apps.order.urls',namespace='order'),name='order'),
        # path('payment/',include('apps.payment.urls',namespace='payment'),name='payment'),
        # path('shipping/',include('apps.shipping.urls',namespace='shipping'),name='shipping'),
       
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

shopproject/onlineshop/templates/partials/footer.html
<footer class="py-5 bg-dark">
    <div class="container">
    <p class="m-0 text-center text-white">
        فروشگاه اینترنتی من  در سال 1403 کار خود را در زمینه انواع لباس ورزشی مردانه و زنانه و همچنین لوازم و تجهیزات ورزشی، با تمرکز بیشتر بر رشته‌های ورزشی فیتنس و بدنسازی شروع کرد. 
         تمرکز ما بر جلب رضایت مشتریان و پشتیبانی قوی از آن‌ها خواهد بود  و در این راستا همواره سعی می نماییم تا بر تنوع کالایی افزوده و کیفیت کارها را اولویت اصلی خودمان قرار دهیم. 
         با رشد روزافزون خرید اینترنتی، تلاش می کنیم تمامی چالش‌های خرید آنلاین را برای مشتریان عزیزمان برطرف سازیم تا با جلب اعتماد مشتریان و صداقت، برند خود را متمایز سازیم. . 
         امیدواریم بتوانیم در کیفیت و سرعت خدمات رضایت شما مشتریان عزیز را فراهم کنیم و گامی در راستای ایجاد رویکردی جدید در ورزش به خصوص فیتنس و بدنسازی برداریم
    </p>
    <br><br>
    <p class="m-0 text-center text-white">ساخته شده با جنگو </p>
</div>
</footer>

shopproject/onlineshop/templates/partials/links.html
<link rel="icon"  href='media/images/icons/favicon64.png' sizes="64x64" /> 
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"  />

shopproject/onlineshop/templates/partials/login_state.html
<ul class="navbar-nav ml-auto " >
    {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href=""> کاربر گرامی <strong style="color:green;">{{user}}</strong> خوش آمدید <span class="sr-only">(current)</span></a>
            </li>
             <li class="nav-item active">
                <a class="nav-link" href=" {% url 'accounts:logout' %}"><strong style="color:red;">خروج</strong><span  class="sr-only">(current)</span></a>
            </li>
    {% else %}
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:login' %}"><strong style="color:red;">ورود</strong><span class="sr-only">(current)</span></a> 
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'accounts:register' %}"><strong style="color:green;">ثبت نام</strong><span class="sr-only">(current)</span></a> 
        </li> 
    {% endif %}
</ul> 

shopproject/onlineshop/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-dismissible fade show text-center" role="alert">
            <h3 class="atert alert-dismissible alert-{{message.tags}} show text-center" role="alert">{{message}}</h3> 
            <button type="button" class="btn-close text-center" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endfor %}
{% endif %}

shopproject/onlineshop/templates/partials/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <!-- search button-->
    <div class="col-div-4">
        <form action="/search/" class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2 font-monospace" name='q' type="search" placeholder="بگرد تا بگردیم   &#128173">
          <button class="btn btn-outline-success my-2 my-sm-0 font-monospace" type="submit">جستجو</button>
        </form>
    </div> 

    <div class="container px-4 px-lg-5"> 
        <a class="navbar-brand font-monospace" href="{% url 'main:index' %}">فروشگاه من</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4 align-right">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'main:index' %}">صفحه اصلی</a></li>

                <!-- dropdown list-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">دسترسی سریع</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item align-center" href="{% url   'main:index' %}">همه محصولات</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item align-center" href="{% url   'products:category_summary' %}">همه دسته بندی ها</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item align-center" href="{% url   'products:sale' %}">تخفیف ویژه</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            <li><a class="dropdown-item align-center" href="{% url   'products:stock' %}">ناموجود</a></li>
                            <li><hr class="dropdown-divider" /></li>
                            {% for category in categories %}
                                <li><a class="dropdown-item align-center" href="{% url 'products:category' category.name %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>

                <!-- dropdown list-->
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">سفارش</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li class="nav-item"><a class="nav-link" href="{% url 'order:create_order' %}">ثبت سفارش</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'order:order_list' %}">نمایش سفارش</a></li>
                    </ul> 
                </li> 
                {% if user.is_authenticated %}  
                    <li class="nav-item"><a class="nav-link" href="{% url 'main:contact' %}">تماس با ما</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">تماس با ما</a></li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{% url 'main:about' %}">درباره ما</a></li>
            </ul>
            <form class="d-flex">
                <a href="{% url 'cart:cart_summary' %}" class="btn btn-outline-dark"> 
                    <i class="bi-cart-fill me-1">سبد خرید</i>
                    <span class="badge bg-dark text-white ms-1 rounded-pill font-monospace" id="cart_quantity">{{cart | length}}</span>
                </a>
            </form>
            {% include "partials/login_state.html" %}
            
        </div> 
    </div>
</nav>

shopproject/onlineshop/templates/partials/paginator.html
<!-- pagination -->
<nav aria-label="page navigation example">
  <ul class="pagination justify-content-center">

    <!-- previous -->
    {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">قبلی</a>
        </li>
    {% endif %}
      
    <!-- page numbers -->
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
            <li class="page-item active" aria-current="page">
                <span class="page-link">
                    {{ i }}
                    <span class="sr-only">(current)</span>
                </span>
            </li>
        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
            <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endif %}
    {% endfor %}
      
    <!-- hellip; -->
    {% if page_obj.number|add:'-4' > 1 %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.number|add:'-5'}}">&hellip;</a>
        </li>
    {% endif %}
    
    <!-- next -->
    {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1" aria-disabled="true">بعدی</a>
        </li>
    {% endif %}
  </ul>
</nav>

shopproject/onlineshop/templates/partials/scripts.html
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>