shopproject/onlineshop/apps/main/urls.py
from django.urls import path
import apps.main.views as views

app_name='main'
urlpatterns=[
    path('',views.ProductList.as_view(),name='index'),
    path('products/',views.ProductList.as_view(),name='products'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('about/',views.about,name='about'),
]
    

shopproject/onlineshop/apps/products/urls.py
from django.urls import path
import apps.products.views as views

app_name='products'
urlpatterns=[
    path('stock/',views.show_stock.as_view(),name='stock'),
    path('product/<int:PK>',views.show_product,name='product'),
    path('category/<str:CAT>',views.show_category,name='category'),
    path('sale/',views.show_sale.as_view(),name='sale'),
    path('product/<int:PK>/add_comment/', views.add_comment, name='add_comment'),
    path('product/<int:PK>/add_rating/', views.add_rating, name='add_rating'),
     path('category/', views.category_summary, name='category_summary'),
]
    
    

shopproject/onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [        
        path('admin/', admin.site.urls),
        path('',include('apps.main.urls',namespace='main'),name='main'),
        path('products/',include('apps.products.urls',namespace='products'),name='products'),
        path('search/',include('apps.search.urls',namespace='search'),name='search'),
        path('accounts/',include('apps.accounts.urls',namespace='accounts'),name='accounts'),
        path('cart/',include('apps.cart.urls',namespace='cart'),name='cart'),
        path('order/',include('apps.order.urls',namespace='order'),name='order'),
        # path('payment/',include('apps.payment.urls',namespace='payment'),name='payment'),
        # path('shipping/',include('apps.shipping.urls',namespace='shipping'),name='shipping'),
       
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

shopproject/onlineshop/apps/main/models.py
from django.db import models
from django.utils import timezone


class Message(models.Model):
    full_name=models.CharField(max_length=60,verbose_name='نام و نام خانوادگی')
    email=models.EmailField(max_length=250,verbose_name='ایمیل')
    subject=models.CharField(max_length=200,verbose_name=' عنوان پیام')
    message=models.TextField(verbose_name='متن پیام')
    is_seen=models.BooleanField(default=False,verbose_name='وضعیت مشاهده توسط مدیر')
    register_date=models.DateTimeField(default=timezone.now,verbose_name='تاریخ ثبت پیام')
    
    def __str__(self):
        return self.full_name+""+self.subject
    class Meta:
        verbose_name='پیام'
        verbose_name_plural='پیام ها'

shopproject/onlineshop/apps/main/forms.py
from django import forms
from .models import Message
from django.forms.utils import ValidationError

    
class MessageForm(forms.ModelForm):
    full_name=forms.CharField(
                                label="نام و نام خانوادگی",
                                error_messages={'required':' این فیلد نمی تواند خالی باشد'},
                                widget=forms.TextInput(attrs={'class':'form-control','placeholder':'نام و نام خانوادگی را وارد کنید',}),
                                
                                )
    
    email = forms.EmailField(label="ایمیل",
                                error_messages={'required':' این فیلد نمی تواند خالی باشد'},
                                widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'ایمیل را وارد کنید'})
                                )
    
    subject = forms.CharField (label="موضوع پیام", 
                                error_messages={'required':' این فیلد نمی تواند خالی باشد'},
                                widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'موضوع پیام را وارد کنید'})
                                )
    message = forms.CharField (label="متن پیام" , 
                                error_messages={'required':' این فیلد نمی تواند خالی باشد'},
                                widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'متن پیام را وارد کنید'})
                                )
    
    class Meta:
        model=Message
        fields=['full_name','email','subject','message']

shopproject/onlineshop/apps/main/views.py
from django.shortcuts import redirect, render
from apps.products.models import Product
from apps.main.models import Message
from django.conf import settings
from django.views.generic.list import ListView
from .forms import MessageForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views import View
################################################################################## 
def media_admin(request):
    return {'media_url':settings.MEDIA_URL,}
################################################################################## 
class ProductList(ListView):
    model = Product
    template_name = 'main/index.html'
    context_object_name = 'products'
    paginate_by = 4

    def get_queryset(self):
        return Product.objects.filter(is_active=True).order_by('-stock')
################################################################################## 
def about(request):
    return render(request,'main/about.html')
################################################################################## 
class ContactView(View):
    template_name="main/contact.html"
    
    def get(self,request,*args,**kwargs): 
        form=MessageForm()
        return render(request,self.template_name,{"form":form})
    
    def post(self,request,*args,**kwargs): 
        form=MessageForm(request.POST)
        if form.is_valid():
            cd=form.cleaned_data
            msg=Message()
            msg.full_name=cd['full_name']
            msg.email=cd['email']
            msg.subject=cd['subject']
            msg.message=cd['message']
            msg.save()
            messages.success(request,"پیام شما ارسال شد","success")
            return redirect("main:index")
        else:
            messages.error(request,"ارسال پیام با خطا مواجه شد","danger") 
            return render(request,self.template_name,{"form":form}) 
################################################################################## 

shopproject/onlineshop/templates/main/about.html
{% extends "maintemplate.html" %}
{% block content  %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">درباره ما</h1>
            <p class="lead fw-normal text-white-50 mb-0">داستان ما را بشنوید !</p>
        </div>
    </div>
</header>
    <br><br>
    <div class=container>
        <div class='row'>
            <center>
                <div class='col-10'>
                    <p align='justify'>
                        لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ، و با استفاده از طراحان گرافیک است، چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است، و برای شرایط فعلی تکنولوژی مورد نیاز، و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد، کتابهای زیادی در شصت و سه درصد گذشته حال و آینده، شناخت فراوان جامعه و متخصصان را می طلبد، تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی، و فرهنگ پیشرو در زبان فارسی ایجاد کرد، در این صورت می توان امید داشت که تمام و دشواری موجود در ارائه راهکارها، و شرایط سخت تایپ به پایان رسد و زمان مورد نیاز شامل حروفچینی دستاوردهای اصلی، و جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.
                    </p>
                </div>
            </center>
        </div>
    </div>
    <br><br>
{% endblock  %}

shopproject/onlineshop/templates/main/contact.html
{% extends 'maintemplate.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}تماس با ما{% endblock %}
{% block content %}
<br><br><br><br>
<div class="site__body align-right">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url "main:index" %}">خانه</a>
                            /
                        </li>
                        <li class="breadcrumb-item active" aria-current="page">تماس با ما</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title">
                <h1>تماس با ما</h1></div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="card mb-0 contact-us">
                <div class="card-body">
                    <div class="contact-us__container">
                        <div class="row">
                            <div class="col-12 col-lg-6 pb-4 pb-lg-0">
                                <h4 class="contact-us__header card-title">آدرس ما</h4>
                                <div class="contact-us__address">
                                    <p><strong>آدرس : </strong>
                                            تهران ، خیابان 
                                        <br><strong>ایمیل :</strong> maryam.zbr@gmail.com
                                        <br><strong>شماره موبایل :</strong> 09122184363</p>
                                    <p><strong>ساعات کاری</strong>
                                        <br>شنبه تا چهارشنبه: 8 صبح - 8 شب
                                        <br>پنجشنبه: 8 صبح - 6 عصر
                                        <br>جمعه: 10 صبح - 4 عصر</p>
                                    <p><strong>دیدگاه</strong>
                                        <br>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی</p>
                                </div>
                            </div>
                            <div class="col-12 col-lg-6">
                                <h4 class="contact-us__header card-title">یک پیام برای ما بگذارید</h4>
                                <form action="" method="post">
                                    {% csrf_token %}
                                    {{form.as_p}}
                                    <input type="submit" value="ارسال پیام" class="btn btn-success btn-block" />
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br><br><br><br><br><br><br><br>
{% endblock %}

shopproject/onlineshop/templates/main/index.html
{% extends "maintemplate.html" %}
{% load static %}
{% load humanize %}
{% block  content %}
<!-- Header-->
<header class="bg-dark py-5"> 
    <div class="container px-4 px-lg-5 my-8">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder font-monospace" >فروشگاه من</h1>
            <p class="lead fw-normal text-white-50 mb-0 font-monospace">به فروشگاه من خوش آمدید</p>
        </div>
    </div> 
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</header>
<!-- Section-->
<section class="py-5">

<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for item in products  %}
        {% if item.is_sale %}
        <div class="col mb-5">
            <div class="card h-100">
                <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">تخفیف ویژه</div>
                <!-- Product image-->
                <img class="card-img-top" src="{{ item.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        <!-- Product price-->
                        دسته بندی : <strong>{{ item.category }}</strong><br>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            {% with ''|center:item.star as range %}
                                {% for _ in range %}
                                    <div class="bi-star-fill"></div>
                                {% endfor %}
                            {% endwith %}
                        </div>
                        {% if item.stock == 0 %}
                            موجودی :<strong> ناموجود </strong>
                            <br>
                            قیمت :<strong> 0 تومان</strong>
                        {% else %}
                            موجودی : <strong>{{item.stock}}</strong><br> 
                            قیمت :
                            <br> 
                            <strike>{{item.price | intcomma:False }} تومان</strike><br>
                            <strong>{{item.sale_price | intcomma:False }} تومان</strong>
                        {% endif %}
                    </div>
                </div>
                <!-- Product actions-->
                {% if item.stock == 0 %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="#">برو به صفحه محصول</a></div>
                    </div> 
                {% else %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary " href="{% url "products:product" item.id %}">برو به صفحه محصول</a></div>
                    </div>
                {% endif %} 
            </div>
        </div>
        {% else %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top" src="{{ item.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        <!-- Product price-->
                            دسته بندی : <strong>{{ item.category }}</strong><br>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            {% with ''|center:item.star as range %}
                            {% for _ in range %}
                                <div class="bi-star-fill"></div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                        {% if item.stock == 0 %}
                            موجودی :<strong> ناموجود </strong> 
                            <br>
                            قیمت : <strong> 0 تومان</strong>
                        {% else %}
                            موجودی : <strong>{{item.stock}}</strong><br>
                            قیمت : 
                            <br>
                            <strong>{{item.price | intcomma:False }} تومان</strong>
                        {% endif %}
                    </div>
                </div>
                <!-- Product actions-->
                {% if item.stock == 0 %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="#">برو به صفحه محصول</a></div>
                    </div> 
                {% else %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="{% url "products:product" item.id %}">برو به صفحه محصول</a></div>
                    </div>
                {% endif %} 
            </div>
        </div> 
        {% endif %}
    {% endfor %}
{% include "partials/paginator.html" %}
</section>
{% endblock  %}