shopproject/onlineshop/apps/accounts/urls.py
from django.urls import path
import apps.accounts.views as views

app_name='accounts'
urlpatterns=[
    path('register/',views.RegisterUserView.as_view(),name='register'),
    path('login/',views.LoginUserView.as_view(),name='login'),
    path('logout/',views.LogoutUserView.as_view(),name='logout'),
    
]
    

shopproject/onlineshop/apps/cart/urls.py
from django.urls import path
import apps.cart.views as views

app_name='cart'
urlpatterns=[
    path('',views.cart_summary,name='cart_summary'),
    path('add/',views.cart_add,name='cart_add'),
    path('delete/',views.cart_delete,name='cart_delete'),
    path('update/',views.cart_update,name='cart_update'),
    
]

shopproject/onlineshop/apps/main/urls.py
from django.urls import path
import apps.main.views as views

app_name='main'
urlpatterns=[
    path('',views.ProductList.as_view(),name='index'),
    path('products/',views.ProductList.as_view(),name='products'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('about/',views.about,name='about'),
]
    

shopproject/onlineshop/apps/products/urls.py
from django.urls import path
import apps.products.views as views

app_name='products'
urlpatterns=[
    path('stock/',views.show_stock.as_view(),name='stock'),
    path('product/<int:PK>',views.show_product,name='product'),
    path('category/<str:CAT>',views.show_category,name='category'),
    path('sale/',views.show_sale.as_view(),name='sale'),
    path('product/<int:PK>/add_comment/', views.add_comment, name='add_comment'),
    path('product/<int:PK>/add_rating/', views.add_rating, name='add_rating'),
     path('category/', views.category_summary, name='category_summary'),
]
    
    

shopproject/onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [        
        path('admin/', admin.site.urls),
        path('',include('apps.main.urls',namespace='main'),name='main'),
        path('products/',include('apps.products.urls',namespace='products'),name='products'),
        path('search/',include('apps.search.urls',namespace='search'),name='search'),
        path('accounts/',include('apps.accounts.urls',namespace='accounts'),name='accounts'),
        path('cart/',include('apps.cart.urls',namespace='cart'),name='cart'),
        path('order/',include('apps.order.urls',namespace='order'),name='order'),
        # path('payment/',include('apps.payment.urls',namespace='payment'),name='payment'),
        # path('shipping/',include('apps.shipping.urls',namespace='shipping'),name='shipping'),
       
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

shopproject/onlineshop/apps/products/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from django.contrib.auth.models import User
from utils import FileUpload
 
# مدل دسته بندی
class Category(models.Model):
    name = models.CharField(max_length=100,verbose_name='نام دسته بندی')

    class Meta:
        verbose_name='دسته بندی'
        verbose_name_plural="دسته بندی ها"
        
    def __str__(self):
        return self.name
    
    
def UploadProductImage(instance,filename):
    return f"images/product/{filename}"  

# مدل برند
class Brand(models.Model):
    name = models.CharField(max_length=100,verbose_name='نام برند')
    
    class Meta:
        verbose_name='برند'
        verbose_name_plural="برندها"
    
    def __str__(self):
        return self.name  
    
# مدل محصول
class Product(models.Model):
    name=models.CharField(max_length=255,verbose_name='نام محصول')
    brand=models.ForeignKey(Brand,on_delete=models.CASCADE,default=1,verbose_name='مارک',blank=True,null=True)
    description = models.TextField(default='',blank=True,null=True,verbose_name='توضیحات محصول')
    price=models.DecimalField(default=0,max_digits=10,decimal_places=0,verbose_name='قیمت محصول')
    category=models.ForeignKey(Category,on_delete=models.CASCADE,default=1,verbose_name='دسته بندی محصول')
    file_upload=FileUpload('images','product')
    image=models.ImageField(upload_to=file_upload.upload_to,verbose_name='تصویر محصول')
    stock=models.IntegerField(default=0,verbose_name='موجودی محصول')
    is_sale=models.BooleanField(default=False,verbose_name='تخفیف')
    sale_price=models.DecimalField(default=0,max_digits=10, decimal_places=0,verbose_name='قیمت تخفیف خورده محصول')
    star=models.IntegerField(default=0,validators=[MaxValueValidator(5),MinValueValidator(0)],verbose_name='امتیاز')
    view_number=models.IntegerField(default=0,verbose_name="تعداد بازدید")
    is_active=models.BooleanField(default=False,verbose_name='وضعیت محصول')
    
    def comment_count(self):
        return self.comments.count()
    
    class Meta:
        verbose_name='محصول'
        verbose_name_plural="محصولات"
        
    def __str__(self):
        return self.name
    
    
def UploadProductImageGallary(instance,filename):
        return f"images/product/gallary/{instance.product.id}/{filename}" 
# مدل گالری تصاویر محصول        
class ProductImageGallary(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE,verbose_name='محصول',related_name='productGallary') 
    image=models.ImageField(upload_to=UploadProductImageGallary,verbose_name='تصویر')

    class Meta:
        verbose_name = 'تصویر'
        verbose_name_plural='تصاویر'


    
# مدل نقد و بررسی
class Comment(models.Model):
    product = models.ForeignKey(Product, related_name='comments', on_delete=models.CASCADE,verbose_name='محصول مورد نقد و بررسی')
    user = models.ForeignKey(User, on_delete=models.CASCADE,verbose_name='کاربر نقد کننده')
    text = models.TextField(verbose_name='متن نقد و بررسی')
    number=models.IntegerField(default=0,verbose_name='تعداد نظرات')
    created_at = models.DateTimeField(auto_now_add=True)
    is_active=models.BooleanField(default=False,verbose_name="وضعیت")

    def __str__(self):
        return f'self.comment.text'
    
    class Meta:
        verbose_name='نقد و بررسی'
        verbose_name_plural="نقدها و بررسی ها" 
        
class Rating(models.Model):
    product=models.ForeignKey(Product,related_name='ratings',on_delete=models.CASCADE,verbose_name='محصول')
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر')
    score=models.IntegerField(validators=[MaxValueValidator(5),MinValueValidator(0)],verbose_name='امتیاز')
    created_at=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name='امتیاز'
        verbose_name_plural="امتیازها"

shopproject/onlineshop/apps/products/forms.py
from django import forms
from .models import Comment,Rating

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

class RatingForm(forms.ModelForm):
    class Meta:
        model=Rating
        fields=['score']
        widgets={
            'score': forms.NumberInput(attrs={'min':1,'max':5})
        }

shopproject/onlineshop/apps/products/views.py
from django.views.generic import ListView
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib import messages
from apps.products.models import Product,Category,Comment,Rating
from django.contrib.auth.decorators import login_required
from .forms import CommentForm,RatingForm
from django.core.paginator import Paginator
################################################################################## 
# تابع برای نمایش محصول با شماره ای دی ارسال شده از طریق پارامتر ورودی
################################################################################## 
def show_product(request,PK):
    
    #  واکشی محصول با شماره ای دی مورد نظر که از طریق پارامتر ورودی ارسال شده است
    product=Product.objects.get(id=PK)
    
    # افزودن تعداد بازدیدهای محصول
    product.view_number+=1
    
    # ذخیره تعداد بازدیدهای محصول در دیتابیس
    product.save()
    
    # واکشی نظرات فعال برای محصول با شماره ای دی مورد نظر
    comments=Comment.objects.filter(product_id=PK,is_active=True)
    
    # صفحه بندی نظرات بصورت 3 تایی
    paginator=Paginator(comments,3)  
    page_number=request.GET.get('page')
    comments=paginator.get_page(page_number)
    
    # امتیاز ثبت شده برای محصول توسط کاربر لاگین شده
    if request.user.is_authenticated:
        user_rating = Rating.objects.filter(product=product,user=request.user).first()
    else:
        user_rating = None
    # ارسال اطلاعات مربوط به محصول - نظرات - امتیاز - تعداد نظرات  به سمت تمپلیت
    context={
        'product':product,
        'comments':comments,
        'comment_count': product.comment_count(),
        'user_rating':user_rating,
    }
    return render(request,'products/product.html',context)
################################################################################## 
def category_summary(request):
    all_category=Category.objects.all()
    return render(request,'products/category_summary.html',{"categories":all_category})
################################################################################## 
def show_category(request,CAT):
    CAT=CAT.replace("-"," ")
    try:
        category=Category.objects.get(name=CAT)
        products=Product.objects.filter(category=category,is_active=True).order_by('-stock')
        context={
            'category':category,
            'products':products
        }
        return render(request,'products/category.html',context)
    except:
        messages.error(request,"(دسته بندی وجود ندارد)")
        return redirect('main:index')
################################################################################## 
def categories_processor(request):
    categories = Category.objects.all()
    return {'categories': categories}
################################################################################## 
class show_sale(ListView):
    model = Product
    template_name = 'products/sale.html'
    context_object_name = 'products'
    paginate_by = 4

    def get_queryset(self):
        return Product.objects.filter(is_sale=True,is_active=True).order_by('-stock')
################################################################################## 
class show_stock(ListView):
    model=Product
    template_name='products/stock.html'
    context_object_name='products'
    paginate_by=4
    
    def get_queryset(self):
        return Product.objects.filter(is_active=True,stock=0)
################################################################################## 
def about(request):
    return render(request,'main/about.html')
################################################################################## 

################################################################################## 
@login_required
def add_comment(request,PK):
    product=Product.objects.get(id=PK)
    if Comment.objects.filter(product=product,user=request.user).exists():
        messages.error(request,"کاربر گرامی " +str(request.user)+" شما قبلا نظر ثبت کرده اید ","warning")
        return redirect('products:product',PK=product.id)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.product=product
            comment.user=request.user
            comment.save()
            messages.success(request," کاربر گرامی " +str(request.user)+"  با تشکر نظر شما پس از بررسی نمایش داده می شود ","success" )
            return redirect('products:product',PK=product.id)
    else:
        form = CommentForm()
    return render(request,'products/add_comment.html',{'form':form,'product':product})
################################################################################## 

################################################################################## 
@login_required
def add_rating(request,PK):
    product=Product.objects.get(id=PK)
    if Rating.objects.filter(product=product,user=request.user).exists():
        messages.error(request,"کاربر گرامی " +str(request.user)+" شما قبلا امتیاز ثبت کرده اید ","warning")
        return redirect('products:product',PK=product.id)
    if request.method=='POST':
        form = RatingForm(request.POST)
        if form.is_valid():
            rating,created=Rating.objects.update_or_create(
                user=request.user,
                product=product,
                defaults={'score':form.cleaned_data['score']}
            )
            messages.success(request,"کاربر گرامی " +str(request.user)+" امتیاز شما ثبت شد ","success")
            return redirect('products:product',PK=product.id)
    else:
        form = RatingForm()
    return render(request,'products/product.html',{'form':form,'product':product})
################################################################################## 

shopproject/onlineshop/templates/products/add_comment.html
{%extends 'maintemplate.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %} {% endblock %}
{% block content %}
<br><br><br><br><br>
<h6 class="text-center"> ثبت نظر برای :<br><br><small>{{ product.name }}</small></h6>
<div class="row justify-content-md-center">
    <form action="" method="POST" class="col-md-6"> 
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="ثبت" class="btn btn-secondary btn-block" >
        <br><br><br><br><br><br><br>
  </form>
</div>
{% endblock %}

shopproject/onlineshop/templates/products/category.html
{% extends "maintemplate.html" %}
{% load static %}
{% load humanize %}
{% block  content %}
<!-- Header-->
<header class="bg-dark py-5">
<div class="container px-4 px-lg-5 my-5">
    <div class="text-center text-white">
        <h1 class="display-4 fw-bolder">{{category}} ها</h1>
        <p class="lead fw-normal text-white-50 mb-0">به سایت من خوش آمدید</p>
    </div>
</div>
</header>
<!-- Section-->
<section class="py-5">
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center:""">
        {% for item in products %}
        {% if item.is_sale %}
        <div class="col mb-5">
            <div class="card h-100">
                <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">تخفیف ویژه</div>
                <!-- Product image-->
                <img class="card-img-top mb-5 mb-md-0" src="{{ item.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        <!-- Product price-->
                        دسته بندی : <strong>{{ item.category }}</strong><br>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                        {% with ''|center:item.star as range %}
                        {% for _ in range %}
                            <div class="bi-star-fill"></div>
                        {% endfor %}
                        {% endwith %}
                    </div>
                        {% if item.stock == 0 %}
                            موجودی :<strong> ناموجود </strong> 
                            <br>
                            قیمت : <strong> 0 تومان</strong>
                        {% else %}
                            موجودی : <strong>{{item.stock}}</strong><br>
                            قیمت : <br>
                            <strike>{{item.price | intcomma:False }} تومان</strike><br>
                            <strong>{{item.price | intcomma:False }} تومان</strong>
                        {% endif %}
                    </div>
                </div>
                <!-- Product actions-->
                {% if item.stock == 0 %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="#">برو به صفحه محصول</a></div>
                    </div> 
                {% else %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="{% url "products:product" item.id %}">برو به صفحه محصول</a></div>
                    </div>
                {% endif %} 
            </div>
        </div>
        {% else %}
        <div class="col mb-5">
            <div class="card h-100">
                <!-- Product image-->
                <img class="card-img-top mb-5 mb-md-0" src="{{ item.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        <!-- Product price-->
                            دسته بندی : <strong> {{ item.category }} </strong><br>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            {% with ''|center:item.star as range %}
                            {% for _ in range %}
                                <div class="bi-star-fill"></div>
                            {% endfor %}
                            {% endwith %}
                        </div>
                        {% if item.stock == 0 %}
                            موجودی :<strong> ناموجود </strong> 
                            <br>
                            قیمت : <strong> 0 تومان</strong>
                        {% else %}
                            موجودی : <strong>{{item.stock}}</strong><br>
                            قیمت : <br>
                            <strong>{{item.price | intcomma:False }} تومان</strong>
                        {% endif %}
                    </div>
                </div>
                <!-- Product actions-->
                {% if item.stock == 0 %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="#">برو به صفحه محصول</a></div>
                    </div> 
                {% else %}
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-secondary" href="{% url "products:product" item.id %}">برو به صفحه محصول</a></div>
                    </div>
                {% endif %} 
            </div>
        </div> 
        {% endif %}
        {% endfor %}
</section>
{% endblock  %}

shopproject/onlineshop/templates/products/category_summary.html
{% extends "maintemplate.html" %}
{% block content  %}
<!-- Header-->
<header class="bg-dark py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">دسته بندی محصولات</h1>
            <p class="lead fw-normal text-white-50 mb-0">دسته بندی های فروشگاه</p>
        </div>
    </div>
</header>
    <br><br>
    <div class=container>
        <div class='row'>
            <center>
                <div class='col-10'>
                    <p align='justify'>
                        {% for category in categories %}
                            <a href="{% url "products:category" category.name  %}">{{category.name}}<br></a>
                        {% endfor %}
                    </p>
                </div>
            </center>
        </div>
    </div>
    <br><br>
{% endblock  %}

shopproject/onlineshop/templates/products/product.html
{% extends "maintemplate.html" %}
{% load static %}
{% load humanize %}
{% block content %}
<!--بخش محصول-->
<br>
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6">
                <img class="card-img-top mb-5 mb-md-0" src='{{ product.image.url }}' alt="..." />
            </div>
            <div class="col-md-6">
                <h6 class="custom-product-name">{{ product.name }}</h6>
                {% autoescape off %}
                    {{ product.description }}
                {% endautoescape %}
                <hr>
                <div class="div">
                    {% if product.is_sale %}
                        قیمت : <strong><strike>{{ product.price | intcomma:False }}</strike></strong> تومان 
                        <br>
                        قیمت : <strong>{{ product.sale_price | intcomma:False }}</strong> تومان 
                    {% else %}
                        قیمت : <strong>{{ product.price | intcomma:False }}</strong> تومان 
                    {% endif %}
                </div>
            
                <p class="align-right">تعداد :</p>
                <select class="form-select" id="cart-qty">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                 </select>
                <br>
                <div class="container">
                    <button class="btn btn-secondary border-0" type="button" value="{{product.id}}" id="add-cart">افزودن به سبد خرید</button>
                    <a href="{% url "main:index" %}" class="btn btn-secondary align-right">بازگشت به صفحه اصلی</a>
                </div>
                <hr>

                <!--بخش دسته بندی و تعداد بازدید محصول-->
                <div class="dir-rtl div">دسته بندی : <strong>{{ product.category }}</strong></div>
                <div class="div">کدمحصول : <strong>{{ product.id }}</strong></div>
                <div class="div">تعداد بازدید : <strong>{{ product.view_number }}</strong></div>
                <hr>

                <!-- لینک برای امتیاز دهی و نظر دهی -->
                <div class="nav nav-tabs">
                    <a class="nav-link active" href="javascript:void(0)" onclick="showSection('rating')">امتیازدهی</a>
                    <a class="nav-link" href="javascript:void(0)" onclick="showSection('comments')">نظر دهی</a>
                </div> 
                <!-- بخش امتیاز دهی -->
                <div id="rating-section">
                    <h5 class="h5 align-center">امتیازات</h5>
                    <div class="div">
                        <form id="rating-form" method="post" action="{% url 'products:add_rating' product.id %}">
                            {% csrf_token %}
                            <div id="star-rating"></div>
                            <input type="hidden" id="rating-score" name="score">
                            <button class="btn btn-secondary" type="submit">ثبت امتیاز</button>
                        </form>
                    </div>

                    <!--نمایش امتیاز ثبت شده توسط کاربر-->
                    {% if user.is_authenticated %}
                        <br>
                        <h6 class="h6">امتیاز ثبت شده شما : <strong>{{ user_rating.score }}</strong></h6>
                    {% endif %}
                </div>

<!--بخش نظردهی-->
<div id="comments-section" style="display: none;">
    <h5 class="h5 align-center">نظرات</h5>
    <small>تعداد نظرات : </small> <strong>{{ comment_count }}</strong>
    <!-- بخش افزودن نظر -->
    <br>
    <h6 class="h6">شما هم نظر بدهید</h6>
        {% if user.is_authenticated %} 
            <div class="d-flex div">
                <div class="text-center">
                    <a  href="{% url "products:add_comment" product.id %}" class="btn btn-secondary">ثبت نظر</a>
                </div>
            </div>
        {% else %}
            <div class="d-flex div">
                <div class="text-center">
                    <a class="btn btn-secondary" href="{% url "accounts:login" %}">ثبت نظر</a>
                </div>
            </div>
        {% endif %} 
    <ul class="ul">
        {% for comment in comments %}
            <li>
                <strong>{{ comment.user.username }}</strong>
                <div class="star-rating small text-warning mb-2">
                    {% with product.ratings.all as ratings %}
                        {% for rating in ratings %}
                            {% if rating.user == comment.user %}
                                {% for _ in ''|center:rating.score %}
                                    <div class="bi-star-fill"></div>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}
                    {% endwith %}
                </div> 
                <h6 class='h6'>{{ comment.text }}</h6>
                <small>{{ comment.created_at }}</small>
            </li>
            <br>
        {% empty %}
            <li class="li">هنوز نظری ثبت نشده است</li>
        {% endfor %}
    </ul>
        
    <!-- صفحه بندی نظرات -->
    <div class="pagination">
        <span class="step-links">
            {% if comments.has_previous %}
                <strong><a href="?page=1&section=comments"> &laquo; اول</a></strong>
                <strong><a href="?page={{ comments.previous_page_number }}&section=comments">قبلی</a></strong>
            {% endif %}
            <span class="current">
                <strong>صفحه {{ comments.number }} از {{ comments.paginator.num_pages }}</strong>
                <br>
            </span>
                {% if comments.has_next %}
                    <strong><a href="?page={{ comments.next_page_number }}&section=comments">بعدی</a></strong>
                    <strong><a href="?page={{ comments.paginator.num_pages }}&section=comments">آخر &raquo; </a></strong>
                {% endif %}
            </span>
        </span>
    </div>          
</div>
</section>
<br><br>

<!-- Add jQuery and jQuery Raty CDN links -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/raty/2.9.0/jquery.raty.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/raty/2.9.0/jquery.raty.css">

<script>
function showSection(section) {
    var ratingSection = document.getElementById('rating-section');
    var commentsSection = document.getElementById('comments-section');
    
    if (section === 'rating') {
        ratingSection.style.display = 'block';
        commentsSection.style.display = 'none';
    } else if (section === 'comments') {
        ratingSection.style.display = 'none';
        commentsSection.style.display = 'block';
    }
}

// چک کردن پارامترهای یو آر ال و نمایش خودکار بخش  امتیازدهی یا نظردهی بر اساس مقدار سکشن
// فراخوانی تابع شو سکشن با مقدار ورودی سکشن
window.onload = function() {
    var urlParams = new URLSearchParams(window.location.search);
    var section = urlParams.get('section');
    if (section) {
        showSection(section);
    }
    
    // مقداردهی ستاره های امتیازدهی
    $('#star-rating').raty({
        path: 'https://cdnjs.cloudflare.com/ajax/libs/raty/2.9.0/images',
        score: function() {
            return $(this).attr('data-score');
        },
        click: function(score, evt) {
            $('#rating-score').val(score);
        }
    });

    // جلوگیری از ارسال فرم بدون ثبت امتیاز
    $('#rating-form').on('submit', function(event) {
        if ($('#rating-score').val() === "") {
            alert("لطفا امتیاز خود را انتخاب کنید.");
            event.preventDefault();
        }
    });
}

</script>
<script>
    $(document).on('click','#add-cart',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url 'cart:cart_add' %}',
            data:{   
                product_id:$('#add-cart').val(),
                product_qty:$('#cart-qty option:selected').text(),
                csrfmiddlewaretoken:'{{csrf_token}}',
                action:'post'
            },
            success: function(json){
                //console.log(json) 
                document.getElementById('cart_quantity').textContent=json.qty

            },
            error: function(xhr, errmsg, err){
        }
        })
    })
</script>
{% endblock %}

shopproject/onlineshop/templates/products/stock.html
{% extends "maintemplate.html" %}
{% load static %}
{% load humanize %}
{% block  content %}
<!-- Header-->
<header class="bg-dark py-5"> 
    <div class="container px-4 px-lg-5 my-8">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder">فروشگاه من</h1>
            <p class="lead fw-normal text-white-50 mb-0">به فروشگاه من خوش آمدید</p>
        </div>
    </div> 
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</header>
<!-- Section-->
<section class="py-5">
    
<div class="container px-4 px-lg-5 mt-5">
    <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
        {% for item in products  %}
        <div class="col mb-5">
            <div class="card h-100">
                <div class="badge bg-danger text-white position-absolute" style="top: 0.5rem; right: 0.5rem">ناموجود</div>
                <!-- Product image-->
                <img class="card-img-top" src="{{ item.image.url }}" alt="..." />
                <!-- Product details-->
                <div class="card-body p-4">
                    <div class="text-center">
                        <!-- Product name-->
                        <h5 class="fw-bolder">{{ item.name }}</h5>
                        <!-- Product price-->
                        دسته بندی : <strong>{{ item.category }}</strong><br>
                        <div class="d-flex justify-content-center small text-warning mb-2">
                            {% with ''|center:item.star as range %}
                                {% for _ in range %}
                                    <div class="bi-star-fill"></div>
                                {% endfor %}
                            {% endwith %}
                        </div>
                        موجودی :<strong> ناموجود </strong><br> 
                        قیمت : <strong>{{0 | intcomma:False }} تومان</strong><br>
                    </div>
                </div>
                <!-- Product actions-->
                <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                    <div class="text-center"><a class="btn btn-secondary" href="#" >برو به صفحه محصول</a></div>
                </div>
            </div>
        </div>
        {% endfor %}
        {% include "partials/paginator.html" %}
</section>
{% endblock  %}