shopproject/onlineshop/apps/cart/urls.py
from django.urls import path
import apps.cart.views as views

app_name='cart'
urlpatterns=[
    path('',views.cart_summary,name='cart_summary'),
    path('add/',views.cart_add,name='cart_add'),
    path('delete/',views.cart_delete,name='cart_delete'),
    path('update/',views.cart_update,name='cart_update'),
    
]

shopproject/onlineshop/apps/main/urls.py
from django.urls import path
import apps.main.views as views

app_name='main'
urlpatterns=[
    path('',views.ProductList.as_view(),name='index'),
    path('products/',views.ProductList.as_view(),name='products'),
    path('contact/',views.ContactView.as_view(),name='contact'),
    path('about/',views.about,name='about'),
]
    

shopproject/onlineshop/onlineshop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [        
        path('admin/', admin.site.urls),
        path('',include('apps.main.urls',namespace='main'),name='main'),
        path('products/',include('apps.products.urls',namespace='products'),name='products'),
        path('search/',include('apps.search.urls',namespace='search'),name='search'),
        path('accounts/',include('apps.accounts.urls',namespace='accounts'),name='accounts'),
        path('cart/',include('apps.cart.urls',namespace='cart'),name='cart'),
        path('order/',include('apps.order.urls',namespace='order'),name='order'),
        # path('payment/',include('apps.payment.urls',namespace='payment'),name='payment'),
        # path('shipping/',include('apps.shipping.urls',namespace='shipping'),name='shipping'),
       
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

shopproject/onlineshop/apps/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from apps.products.models import Product

# مدل سبد خرید  
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='کاربر ایجاد کننده سبد خرید ')
    total_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='روش حمل و نقل')
    created_at = models.DateTimeField(auto_now_add=True,verbose_name='تاریخ و زمان ایجاد سبد خرید')
    updated_at = models.DateTimeField(auto_now=True,verbose_name='تاریخ و زمان آخرین بروزرسانی سبد خرید')

    class Meta:
        verbose_name='سبد خرید'
        verbose_name_plural="سبدهای خرید" 
        
class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items',verbose_name='لیست سبد خرید') # شامل محصول تعداد و قیمت واحد
    product = models.ForeignKey(Product, on_delete=models.CASCADE,verbose_name='محصول سبد خرید')
    quantity = models.PositiveIntegerField(verbose_name='تعداد محصول سبد خرید')
    unit_price = models.DecimalField(max_digits=10, decimal_places=2,verbose_name='قیمت واحد محصول سبد خرید')

    class Meta:
        verbose_name='کالای سبد خرید'
        verbose_name_plural="کالاهای سبد خرید"

shopproject/onlineshop/apps/cart/views.py
from django.shortcuts import render,get_object_or_404
from .cart import Cart
from .models import Product
from django.http import JsonResponse
################################################################################## 
def cart_processor(request):
    return {'cart':Cart(request)} 
################################################################################## 
def cart_summary(request):
    cart=Cart(request)
    cart_products=cart.get_prods()
    quantities=cart.get_quants()
    total=cart.get_total()
    return render(request,'cart/cart_summary.html',{'cart_products':cart_products,'quantities':quantities,'total':total})
################################################################################## 
def cart_add(request):
    cart=Cart(request)
    if request.POST.get('action')=='post':
        product_id=int(request.POST.get('product_id'))
        product_qty=int(request.POST.get('product_qty'))
        product=get_object_or_404(Product,id=product_id)
        cart.add(product=product,quantity=product_qty) 
        cart_quantity=cart.__len__()
        response=JsonResponse({'qty':cart_quantity})
        return response
##################################################################################     
def cart_update(request):
    cart=Cart(request)
    if request.POST.get('action')=='post':
        product_id=int(request.POST.get('product_id'))
        product_qty=int(request.POST.get('product_qty'))
        cart.update(product=product_id,quantity=product_qty)  
        response=JsonResponse({'qty':product_qty})
        return response
##################################################################################    
def cart_delete(request):
    cart=Cart(request)
    if request.POST.get('action')=='post':
        product_id=int(request.POST.get('product_id'))
        cart.delete(product=product_id)  
        response=JsonResponse({'product':product_id})
        return response

shopproject/onlineshop/templates/cart/cart_summary.html
{% extends "maintemplate.html" %}
{% load static %}
{% load humanize %}
{% block  content %}
<!-- Header-->
<header class="bg-dark py-5"> 
    <div class="container px-4 px-lg-5 my-8">
        <div class="text-center text-white">
            <h1 class="display-4 fw-bolder font-monospace">سبد خرید شما</h1>
        </div>
    </div> 
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</header>
<section class="py-5">
{% if cart_products %}
    {% for product in cart_products  %}
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6">
                    <img class="card-img-top mb-5 mb-md-0" src='{{ product.image.url }}' alt="..." />
                </div>
                <div class="col-md-6">
                    <h6 class="custom-product-name">{{ product.name }}</h6>
                    {% autoescape off %}
                        {{ product.description }}
                    {% endautoescape %}
                    <hr>
                    <div class="div">
                        {% if product.is_sale %}
                            قیمت : <strong><strike>{{ product.price | intcomma:False }}</strike></strong> تومان 
                            <br>
                            قیمت : <strong>{{ product.sale_price | intcomma:False }}</strong> تومان 
                        {% else %}
                            قیمت : <strong>{{ product.price | intcomma:False }}</strong> تومان 
                        {% endif %}
                    </div>
                    <div class="d-flex div align-right">
                        تعداد :
                    </div>
                    <select class="form-select" id="select{{product.id}}">
                        {% for key,value in quantities.items %}
                            {% if key == product.id|slugify %}
                                <option selected>{{value}}</option>
                            {% endif %}
                        {% endfor %}
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                    </select>
                </div>
            </div>
            <br>
            <button type="button" data-index={{product.id}} class="btn btn-primary update-cart">ویرایش</button>
            <button type="button" data-index={{product.id}} class="btn btn-danger delete-product">حذف</button>
            <a href="{% url "main:index" %}" class="btn btn-secondary align-center">بازگشت به صفحه اصلی</a>
            <hr>
        </div>    
        </section> 
    {% endfor %} 
    <h3 class="align-center font-monospace text-bg-success">مجموع سفارشات: <strong >{{total | intcomma:False}}</strong></h3>
{% else %}
    <br><br><br><br><br><br>
    <center><h3 class="container"> &#128546;سبد خرید شما خالی است</h3></center>
{% endif %}
<script>
    $(document).on('click','.update-cart',function(e){
        e.preventDefault();
        var productid=$(this).data('index');
        $.ajax({
            type:'POST',
            url:'{% url 'cart:cart_update' %}',
            data:{   
                product_id:$(this).data('index'),
                product_qty:$('#select'+productid+' option:selected').text(),
                csrfmiddlewaretoken:'{{csrf_token}}',
                action:'post'
            },
            success: function(json){
                location.reload();
            },
            error: function(xhr, errmsg, err){
        }
        })
    })


    $(document).on('click','.delete-product',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url 'cart:cart_delete' %}',
            data:{   
                product_id:$(this).data('index'),
                csrfmiddlewaretoken:'{{csrf_token}}',
                action:'post'
            },
            success: function(json){
                location.reload();
            },
            error: function(xhr, errmsg, err){
        }
        })
    })
</script>
{% endblock  %}